# Generated by Django 4.1.12 on 2023-12-15 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_alter_order_book_id_alter_order_order_id_and_more'),
        ('address', '0002_alter_address_address_id_alter_address_user_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.UUID('194b37d0-8c32-4727-a08c-4b1c6ef3e728'), editable=False, primary_key=True, serialize=False)),
                ('address_id', models.ForeignKey(default=uuid.UUID('48b07ca2-e7fd-40a0-9068-286ffbd0990e'), on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('order_id', models.ForeignKey(default=uuid.UUID('9cbd137e-a7eb-4b90-878b-f0df4910cf1d'), on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user_id', models.ForeignKey(default=uuid.UUID('020d3703-b930-44f2-9da2-2a7824628dad'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
