# Generated by Django 4.1.12 on 2023-12-18 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_alter_order_book_id_alter_order_order_id_and_more'),
        ('address', '0002_alter_address_address_id_alter_address_user_id'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.UUID('13ffc668-e8d2-416c-a464-c165475c9ce9'), editable=False, primary_key=True, serialize=False)),
                ('address_id', models.ForeignKey(default=uuid.UUID('48ca3719-1429-4139-a0d7-61b239cd28e5'), on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('order_id', models.ForeignKey(default=uuid.UUID('063cbcdf-8089-40ff-a710-428c045ea513'), on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user_id', models.ForeignKey(default=uuid.UUID('4c934939-666a-407f-b5e5-73895450b528'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
