# Generated by Django 4.1.12 on 2023-12-15 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.UUID('08a7d34a-c9c8-4969-8e94-8cbc7b9183a3'), editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=500)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=50)),
                ('user_id', models.ForeignKey(default=uuid.UUID('ec19ad7d-5eeb-49da-87e8-06d70352e088'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
