# Generated by Django 4.1.12 on 2023-12-18 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.UUID('c8d21cff-f114-4a68-8ca0-57765a7f7090'), editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=500)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=50)),
                ('user_id', models.ForeignKey(default=uuid.UUID('ad5c7d00-7457-491d-bd5a-a74f4bf4c015'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
