# Generated by Django 4.1.12 on 2023-12-15 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default=uuid.UUID('02fc8539-796b-4c21-89e6-c7e6309ee6bc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(default=uuid.UUID('d9ac76a0-9a90-4bc6-ad95-de9375f07f68'), on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
