# Generated by Django 4.1.12 on 2023-12-18 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.UUID('590837b3-c147-460d-b785-663c53fbdbe3'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('publication_date', models.DateField()),
                ('ISBN', models.CharField(max_length=13)),
                ('genre', models.CharField(max_length=225)),
                ('cover_image', models.CharField(max_length=225)),
                ('summery', models.CharField(max_length=10000)),
                ('price', models.BigIntegerField()),
                ('page_count', models.IntegerField()),
                ('rating', models.FloatField(max_length=2)),
                ('author', models.CharField(max_length=225)),
                ('edition', models.BigIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_ebook_available', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
