# Generated by Django 4.1.12 on 2023-12-21 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.UUID('a442be89-9fe1-4509-b2be-9b761b7ea952'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('publication_date', models.DateField()),
                ('ISBN', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=225)),
                ('cover_image', models.CharField(max_length=225)),
                ('summary', models.CharField(max_length=10000)),
                ('price', models.FloatField()),
                ('page_count', models.IntegerField()),
                ('rating', models.FloatField(max_length=2)),
                ('author', models.CharField(max_length=225)),
                ('edition', models.BigIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_ebook_available', models.BooleanField(default=False)),
            ],
        ),
    ]
