# Generated by Django 4.1.12 on 2023-12-21 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('7ec021bb-88af-457f-b59b-11539ee7763c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
