# Generated by Django 4.1.12 on 2023-12-15 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('book', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.UUID('e6b74a7c-66c9-4cd3-b788-245cbd23ab3c'), editable=False, primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(default=uuid.UUID('35e5e686-cdde-4e24-9022-59782cab0e67'), on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(default=uuid.UUID('dcc2ee7a-1c7d-42f0-ad47-e54a2c9b6c60'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
