# Generated by Django 4.1.12 on 2023-12-18 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '__first__'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.UUID('acaf9e2e-92ce-484c-9676-96838cfdd7ed'), editable=False, primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(default=uuid.UUID('703a0ef0-55b3-4774-a65d-3825603c740b'), on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(default=uuid.UUID('cf48e2ac-1544-4cd7-a766-efabeb5b968e'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
