# Generated by Django 4.1.12 on 2023-12-21 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.UUID('75ade50f-bad5-40df-a085-3fa7d02e5642'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(default=uuid.UUID('6949e354-fc8d-4a7b-9433-bc582eee0051'), on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(default=uuid.UUID('cd0b2c78-498b-4803-8ea5-3b01dcb90f66'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
