# Generated by Django 4.1.12 on 2023-12-15 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=225)),
                ('user_email', models.EmailField(max_length=225)),
                ('user_number', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
