# Generated by Django 4.1.12 on 2023-12-18 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '__first__'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.UUID('117d6a06-fcbf-4531-8200-a76766ebd13b'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now=True)),
                ('book_id', models.ForeignKey(default=uuid.UUID('911fcbd7-129d-4722-87cf-8bccf8622258'), on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(default=uuid.UUID('cffee062-590e-4893-8e9d-c4afa8575bf9'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
