# Generated by Django 4.1.12 on 2023-12-15 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.UUID('81c4d16f-3512-4898-ad20-18751c696582'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now=True)),
                ('book_id', models.ForeignKey(default=uuid.UUID('900bf2fd-7605-4d2b-8d04-ed62560bc0cd'), on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user_id', models.ForeignKey(default=uuid.UUID('cb66c0bd-fc03-4840-8c77-4551ab0a08e1'), on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
