# Generated by Django 4.1.12 on 2023-12-18 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '__first__'),
        ('user', '__first__'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_id',
            field=models.ForeignKey(default=uuid.UUID('c2621e50-8cd2-4c62-949b-6e105be52326'), on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('bca39b29-9187-46f3-be6d-e120da7aacf8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=uuid.UUID('941d418d-f32d-42ed-8b40-fd0f3a411008'), on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
