# Generated by Django 4.1.12 on 2023-12-15 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '__first__'),
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_id',
            field=models.ForeignKey(default=uuid.UUID('e72a5eaf-23dc-47bc-a39c-78bf1a32b730'), on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('c9529bb1-e220-415b-8cd4-ebd5a9d37cee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=uuid.UUID('794f64e8-1111-45f6-8add-a158365336a2'), on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
